---
# defaults file for monitor_cluster

monitor: True
secure: False

cluster_id: "{{ hostvars['bastion']['cluster_id'] }}"

ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] | default(ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])) }}"
ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] | default(8090) }}"
ASSISTED_INSTALLER_BASE_URL: "{{ secure | ternary('https', 'http') }}://{{ ASSISTED_INSTALLER_HOST }}:{{ ASSISTED_INSTALLER_PORT }}/api/assisted-install/v1"
URL_ASSISTED_INSTALLER_CLUSTER: "{{ ASSISTED_INSTALLER_BASE_URL }}/clusters/{{ cluster_id }}"

# HTTP Basic Authentication
HTTP_AUTH_USERNAME: "none"
HTTP_AUTH_PASSWORD: "none"

waiting_termination_states:
  - "installing-pending-user-action"
