- name: Create inventory host to vm name mapper
  set_fact:
    cluster_vm_names: "{{ (cluster_vm_names | default([])) + [item.startswith(cluster_name) | ternary(item, (cluster_name + '_' + item))] }}"
  loop: "{{ groups['nodes']) }}"
  when: hostvars[item]['vendor'] | lower == 'kvm'

- debug: # noqa unnamed-task
    var: vm_to_inventory_mapper
    verbosity: 1

- name: Setup host environment
  become: true
  block:
    - name: "Install virt-manager"
      package:
        name: "{{ virt_packages }}"
        state: present

    - name: Start libvirtd
      service:
        name: libvirtd
        state: started

- name: Destroy vms
  import_tasks: destroy_networks.yml
  become: true

- name: Get VMs to Remove
  block:
    - name: List vms
      community.libvirt.virt:
        command: list_vms
      register: vms_list
      become: true

    - name: VM list
      debug:
        var: vms_list.list_vms
        verbosity: 1

    - name: Get filtered vm list
      set_fact:
        vms_to_remove: "{{ (vms_to_remove | default([])) + [item] }}"
      loop: "{{ vms_list.list_vms }}"
      when: item in cluster_vm_names

- name: VMS to remove
  debug:
    var: vms_to_remove
    verbosity: 1

- name: Destroy vms
  import_tasks: destroy_vms.yml
  ignore_errors: yes
  become: true
