assisted_service_image_repo: "edge-infrastructure"
assisted_service_image_repo_url: "quay.io/{{ assisted_service_image_repo }}"

assisted_service_image: "{{ assisted_service_image_repo_url }}/assisted-service@{{ image_hashes.service }}"
assisted_service_gui_image: "{{ assisted_service_image_repo_url }}/assisted-installer-ui@{{ image_hashes.gui }}"
assisted_service_image_service_image: "{{ assisted_service_image_repo_url }}/assisted-image-service@{{ image_hashes.image_service }}"

assisted_service_controller_image: "{{ assisted_service_image_repo_url }}/assisted-installer-controller@{{ image_hashes.controller }}"
assisted_service_installer_agent_image: "{{ assisted_service_image_repo_url }}/assisted-installer-agent@{{ image_hashes.installer_agent }}"
assisted_service_installer_image: "{{ assisted_service_image_repo_url }}/assisted-installer@{{ image_hashes.installer }}"
assisted_postgres_image: quay.io/centos7/postgresql-12-centos7:latest
assisted_installer_dir: /opt/assisted-installer
assisted_installer_data_dir: "{{ assisted_installer_dir }}/data"

assisted_installer_hardware_validation:
- version: default
  master:
    cpu_cores: 4
    ram_mib: 16384
    disk_size_gb: 120
    installation_disk_speed_threshold_ms: 10
    network_latency_threshold_ms: 100
    packet_loss_percentage: 0
  worker:
    cpu_cores: 2
    ram_mib: 8192
    disk_size_gb: 120
    installation_disk_speed_threshold_ms: 10
    network_latency_threshold_ms: 1000
    packet_loss_percentage: 10
  sno:
    cpu_cores: 8
    ram_mib: 16384
    disk_size_gb: 120
    installation_disk_speed_threshold_ms: 10

dns_servers: "{% if dns is defined %}{{ [dns] }}{% else %}{{ [] }}{% endif %}"
assisted_service_host: "{{ host | default('ansible_fqdn') }}" # nodes -> assisted service
image_service_host: "{{ host | default('ansible_fqdn') }}" # bastion -> image service

use_local_mirror_registry: "{{ setup_registry_service | default(False) }}"

config_file_path: /tmp/wip/config
port: 8090

# Proxy settings for the AI Pod configuration.
http_proxy: ""
https_proxy: ""
no_proxy: ""

podman_ipv6_network_subnet: 'fd00::1:8:0/112'
podman_ipv6_network_gateway: 'fd00::1:8:1'
