---
- name: Assert that all credentials for the disconnected registry are set
  assert:
    that:
      - hostvars['registry_host'][secret_var_name] is defined
      - hostvars['registry_host'][secret_var_name] is string
      - hostvars['registry_host'][secret_var_name] | trim != ''
    fail_msg: >
      The registry host requires a valid {{ secret_var_name }} variable to be set.
      Please ensure a valid secret is set in the inventory vault file.
  vars:
    secret_vars_to_check:
      - disconnected_registry_user
      - disconnected_registry_password
      - REGISTRY_HTTP_SECRET
  loop: "{{ secret_vars_to_check }}"
  loop_control:
    loop_var: secret_var_name
  # only for Restricted Network installations
  when: "use_local_mirror_registry | default(setup_registry_service | default(true))"

- name: Assert that all nodes have BMC credentials set
  assert:
    that:
      - hostvars[item.0][item.1] is defined
      - hostvars[item.0][item.1] is string
      - hostvars[item.0][item.1] | trim != ''
    fail_msg: >
      Node {{ item.0 }} requires a valid {{ item.1 }} variable to be set.
      Please ensure valid BMC credentials are set in the inventory vault file.
  vars:
    secret_vars_to_check:
      - bmc_user
      - bmc_password
    nodes_and_required_secret_vars: "{{ groups['nodes'] | product(secret_vars_to_check) | list }}"
  loop: "{{ nodes_and_required_secret_vars }}"
