ai_version: v1.0.24.2
controller_tag: "{{ ai_version }}"
installer_agent_tag: "{{ ai_version }}"
installer_tag: "{{ ai_version }}"

ocp_release_versions_map_all:
  '4.6': 4.6.16
  '4.7': 4.7.33
  '4.8': 4.8.14
  '4.9': 4.9.11
  '4.10': 4.10.10

get_release_images: true
get_all_release_versions: false

ocp_release_versions_map: "{{ get_all_release_versions | ternary(ocp_release_versions_map_all, {openshift_version: ocp_release_versions_map_all[openshift_version]}) }}"

release_image_url: "quay.io/openshift-release-dev/ocp-release"

assisted_installer_images:
  controller:
    image: quay.io/edge-infrastructure/assisted-installer-controller
    tag: "{{ controller_tag }}"
  installer_agent:
    image: quay.io/edge-infrastructure/assisted-installer-agent
    tag: "{{ installer_agent_tag }}"
  installer:
    image: quay.io/edge-infrastructure/assisted-installer
    tag: "{{ installer_tag }}"

images_to_get_hash_for: "{{ assisted_installer_images | combine(release_images | default({})) }}"

destination_hosts:
  - registry_host
  - assisted_installer
