ai_version: v2.12.1
controller_tag: "{{ ai_version }}"
installer_agent_tag: "{{ ai_version }}"
installer_tag: "{{ ai_version }}"
assisted_service_tag: "{{ ai_version }}"
assisted_service_gui_tag: "{{ ai_version }}"
assisted_service_image_service_tag: "{{ ai_version }}"

get_release_images: true
get_all_release_versions: false

images_to_get_hash_for: "{{ assisted_installer_images | combine(processed_release_images | default({})) }}"

destination_hosts:
  - registry_host
  - assisted_installer

image_hashes_path: "{{ repo_root_path }}/image_hashes.yml"
ignore_cached_image_hashes: false
image_hashes: {}

os_images:
  - openshift_version: '4.6'
    cpu_architecture: x86_64
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso
    rootfs_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img
    version: 46.82.202012051820-0
  - openshift_version: '4.7'
    cpu_architecture: x86_64
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.33/rhcos-4.7.33-x86_64-live.x86_64.iso
    rootfs_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.33/rhcos-live-rootfs.x86_64.img
    version: 47.84.202109241831-0
  - openshift_version: '4.8'
    cpu_architecture: x86_64
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live.x86_64.iso
    rootfs_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-live-rootfs.x86_64.img
    version: 48.84.202109241901-0
  - openshift_version: '4.9'
    cpu_architecture: x86_64
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.45/rhcos-4.9.45-x86_64-live.x86_64.iso
    rootfs_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.45/rhcos-live-rootfs.x86_64.img
    version: 49.84.202208012046-0
  - openshift_version: '4.10'
    cpu_architecture: x86_64
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/4.10.37/rhcos-4.10.37-x86_64-live.x86_64.iso
    rootfs_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/4.10.37/rhcos-4.10.37-x86_64-live-rootfs.x86_64.img
    version: 410.84.202210061459-0
  - openshift_version: '4.11'
    cpu_architecture: x86_64
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-x86_64-live.x86_64.iso
    rootfs_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-x86_64-live-rootfs.x86_64.img
    version: 411.86.202210072320-0
  - openshift_version: '4.12'
    cpu_architecture: x86_64
    url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/4.12.3/rhcos-4.12.3-x86_64-live.x86_64.iso
    rootfs_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/4.12.3/rhcos-4.12.3-x86_64-live-rootfs.x86_64.img
    version: 412.86.202302091057-0
  - openshift_version: '4.12'
    cpu_architecture: arm64
    url: https://mirror.openshift.com/pub/openshift-v4/arm64/dependencies/rhcos/4.12/4.12.3/rhcos-4.12.3-aarch64-live.aarch64.iso
    rootfs_url: https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.12/4.12.3/rhcos-4.12.3-aarch64-live-rootfs.aarch64.img
    version: 412.86.202302091057-0

release_images:
  - openshift_version: '4.6'
    cpu_architecture: x86_64
    url: quay.io/openshift-release-dev/ocp-release:4.6.16-x86_64
    version: 4.6.16
  - openshift_version: '4.7'
    cpu_architecture: x86_64
    url: quay.io/openshift-release-dev/ocp-release:4.7.52-x86_64
    version: 4.7.52
  - openshift_version: '4.8'
    cpu_architecture: x86_64
    url: quay.io/openshift-release-dev/ocp-release:4.8.43-x86_64
    version: 4.8.43
  - openshift_version: '4.9'
    cpu_architecture: x86_64
    url: quay.io/openshift-release-dev/ocp-release:4.9.45-x86_64
    version: 4.9.45
  - openshift_version: '4.10'
    cpu_architecture: x86_64
    url: quay.io/openshift-release-dev/ocp-release:4.10.37-x86_64
    version: 4.10.37
    default: true
  - openshift_version: '4.11'
    cpu_architecture: x86_64
    url: quay.io/openshift-release-dev/ocp-release:4.11.24-x86_64
    version: 4.11.24
  - openshift_version: '4.12'
    cpu_architecture: x86_64
    url: quay.io/openshift-release-dev/ocp-release:4.12.4-x86_64
    version: 4.12.4
  - openshift_version: '4.12'
    cpu_architecture: arm64
    url: quay.io/openshift-release-dev/ocp-release:4.12.4-aarch64
    version: 4.12.4

assisted_service_image_repo_url: quay.io/edge-infrastructure

assisted_installer_images:
  controller:
    url: "{{ assisted_service_image_repo_url }}/assisted-installer-controller:{{ controller_tag }}"
  installer_agent:
    url: "{{ assisted_service_image_repo_url }}/assisted-installer-agent:{{ installer_agent_tag }}"
  installer:
    url: "{{ assisted_service_image_repo_url }}/assisted-installer:{{ installer_tag }}"
  service:
    url: "{{ assisted_service_image_repo_url }}/assisted-service:{{ assisted_service_tag }}"
  gui:
    url: "{{ assisted_service_image_repo_url }}/assisted-installer-ui:{{ assisted_service_gui_tag }}"
  image_service:
    url: "{{ assisted_service_image_repo_url }}/assisted-image-service:{{ assisted_service_image_service_tag }}"
