---
# defaults file for generate_discovery_iso

secure: False
generate: True
download: True
upload: False

disconnected: "{{ use_local_mirror_registry | default(setup_registry_service | default(true)) }}"
mirror_registry: "{{ hostvars['registry_host']['registry_fqdn'] }}:{{ hostvars['registry_host']['registry_port'] }}"
ocp_registry_namespace: "{{ hostvars['registry_host']['registry_namespace'] | default('ocp4') }}"
ocp_registry_image: "{{ hostvars['registry_host']['registry_image'] | default('openshift4') }}"
registry_repository: "{{ ocp_registry_namespace }}/{{ ocp_registry_image }}"

ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] | default(ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])) }}"
ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] | default(8090) }}"
ASSISTED_INSTALLER_BASE_URL: "{{ secure | ternary('https', 'http') }}://{{ ASSISTED_INSTALLER_HOST }}:{{ ASSISTED_INSTALLER_PORT }}/api/assisted-install/v2"
ASSISTED_INSTALLER_CLUSTER: "{{ ASSISTED_INSTALLER_BASE_URL }}/clusters/{{ iso_cluster_id }}"
# URL_ASSISTED_INSTALLER_CLUSTERS_DOWNLOAD_IMAGE: "{{ ASSISTED_INSTALLER_CLUSTER }}/downloads/image"
iso_cluster_id: "{{ cluster_id }}"

# HTTP Basic Authentication
HTTP_AUTH_USERNAME: "none"
HTTP_AUTH_PASSWORD: "none"

ssh_public_key: ""
DOWNLOAD_DEST_FILE: "{{ discovery_iso_name }}"
DOWNLOAD_DEST_PATH: "{{ iso_download_dest_path | default('/opt/http_store/data') }}"

mac_interface_default_mapping: "interfaces[?(name != null && mac != null)].{logical_nic_name: name, mac_address: mac}"
ai_version: "{{ hostvars.assisted_installer.ai_version | default('v2.12.1') }}"
ai_version_number: "{{ ai_version | regex_replace('v(\\d+\\.\\d+\\.\\d+)', '\\1') }}"

http_proxy: ""
https_proxy: ""
no_proxy: ""

use_hostname_workaround: false
