---
- name: Verify the certificate variables are set
  ansible.builtin.assert:
    that:
      - item is defined
      - item is string
      - item | trim != ''
    quiet: true
  loop:
    - "{{ cert_common_name }}"
    - "{{ cert_country }}"
    - "{{ cert_state }}"
    - "{{ cert_locality }}"
    - "{{ cert_organization }}"
    - "{{ cert_organizational_unit }}"

- name: Install python3-cryptography
  ansible.builtin.package:
    name: python3-cryptography
    state: present
  become: true

- name: Create directory to hold the cert files
  ansible.builtin.file:
    path: "{{ cert_dir }}"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: 0770
    state: directory
    recurse: true
  become: true

- name: Generate an OpenSSL private key
  community.crypto.openssl_privatekey:
    path: "{{ privatekey_path }}"


- name: Generate an OpenSSL CSR
  community.crypto.openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ privatekey_path }}"
    common_name: "{{ cert_common_name }}"
    country_name: "{{ cert_country }}"
    state_or_province_name: "{{ cert_state }}"
    locality_name: "{{ cert_locality }}"
    organization_name: "{{ cert_organization }}"
    organizational_unit_name: "{{ cert_organizational_unit }}"
    basic_constraints_critical: true
    create_subject_key_identifier: true
    basic_constraints: ["CA:TRUE"]

- name: Generate a selfsigned OpenSSL CA Certificate
  community.crypto.x509_certificate:
    path: "{{ ownca_path }}"
    privatekey_path: "{{ privatekey_path }}"
    csr_path: "{{ csr_path }}"
    provider: selfsigned

- name: Generate an ownca OpenSSL Certificate
  community.crypto.x509_certificate:
    path: "{{ cert_path }}"
    ownca_privatekey_path: "{{ privatekey_path }}"
    csr_path: "{{ csr_path }}"
    ownca_path: "{{ ownca_path }}"
    ownca_create_authority_key_identifier: true
    provider: ownca

- name: Set cert in CA trust
  become: true
  block:
    - name: Copy cert to pki directory
      ansible.builtin.copy:
        src: "{{ cert_path }}"
        dest: /etc/pki/ca-trust/source/anchors/{{ cert_file_prefix }}.crt
        remote_src: true
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: 0660
        force: true
        backup: true

    - name: Update the CA trust files
      ansible.builtin.command:
        cmd: update-ca-trust extract

- name: Fetch the domain cert from the registry host
  ansible.builtin.fetch:
    src: "{{ cert_path }}"
    dest: "{{ fetched_dest }}/{{ cert_file_prefix }}.crt"
    flat: true
  tags:
    - copy_config
