---

# Paths
config_file_path: "{{ ansible_env.HOME }}" # Where config and secret files should be stored
fetched_dest: "{{ repo_root_path }}/fetched"

# defaults file for disconnected_registry
pull_secret_file_name: pull-secret.txt

# defaults file for disconnected_registry
force: "no" # force downloads for oc and opm

openshift_version: "{{ openshift_full_version.split('.')[:2] | join('.') }}"
downloads_path: "{{ ansible_env.HOME }}"

# Name of the pod running as the registry.
image_name_registry: ocpdiscon-registry

# oc and opm install
release_url: "https://mirror.openshift.com/pub/openshift-v{{ openshift_version_parts[0] }}/clients/ocp"
oc_tar: openshift-client-linux.tar.gz
opm_tar: opm-linux.tar.gz

# The information for the locally created registry
registry_fqdn: "{{ ansible_fqdn }}"
local_registry: "{{ registry_fqdn }}:{{ registry_port }}"
registry_port: 5000

installer_agent_image:
  remote: "quay.io/edge-infrastructure/assisted-installer-agent@{{ image_hashes.installer_agent }}"
  local: "{{ local_registry }}/ocpmetal/assisted-installer-agent"
  local_tag: "latest"

installer_image:
  remote: "quay.io/edge-infrastructure/assisted-installer@{{ image_hashes.installer }}"
  local: "{{ local_registry }}/ocpmetal/assisted-installer"
  local_tag: "latest"

installer_controller_image:
  remote: "quay.io/edge-infrastructure/assisted-installer-controller@{{ image_hashes.controller }}"
  local: "{{ local_registry }}/ocpmetal/assisted-installer-controller"
  local_tag: "latest"

release_image_remote: "quay.io/openshift-release-dev/ocp-release"

release_image_item:
  remote: "{{ release_image_remote }}@{{ image_hashes['release_' + (openshift_full_version | string) + '_x86_64'] }}"
  local: "{{ local_registry }}/ocp4/openshift4"
  local_tag: "{{ openshift_full_version }}-x86_64"

arm_release_image_key: "release_{{ openshift_full_version | string }}_arm64"

release_image_item_arm:
  remote: "{{ release_image_remote }}@{{ image_hashes[arm_release_image_key] }}"
  local: "{{ local_registry }}/ocp4/openshift4"
  local_tag: "{{ openshift_full_version }}-aarch64"

olm_index_item:
  remote: "registry.redhat.io/redhat/redhat-operator-index:v{{ openshift_version }}"
  local: "{{ local_registry }}/olm-index/redhat-operator-index"
  local_tag: "v{{ openshift_version }}"

olm_item:
  local: "{{ local_registry }}/olm"
  local_tag: "v{{ openshift_version }}"

ocpmetal_images:
  - "{{ installer_agent_image }}"
  - "{{ installer_image }}"
  - "{{ installer_controller_image }}"

populate_operator_catalog: false
mirror_packages:
  - advanced-cluster-management
  - cluster-logging
  - kubevirt-hyperconverged
  - local-storage-operator
  - ocs-operator
  - performance-addon-operator
  - ptp-operator
  - sriov-network-operator

file_owner: "{{ ansible_env.USER }}"
file_group: "{{ file_owner }}"
