virt_packages:
  - python3
  - libvirt
  - virt-install
  - qemu-kvm
  - virt-manager
  - python3-pip
  - python3-lxml
  - python3-libvirt

images_dir: /var/lib/libvirt/images/
vm_create_scripts: /home/redhat/vm_create_scripts/

bridge_name: "{{ cluster_name }}-br"
network_name: "net-{{ cluster_name }}"
