---
# tasks file for boot_disk

- name: Join list for workers and masters
  set_fact:
    hosts: "{{ groups['masters'] + groups['workers'] | default([]) }}"
  when: hosts is not defined

- name: Boot from disk for "{{ hostvars[item]['vendor'] }}"
  include_role: 
    name: "vendors/{{ hostvars[item]['vendor'] | lower }}"
    tasks_from: disk.yml
  loop: "{{ hosts }}"
