---
- name: UnMount Live ISO, Boot into HDD (SuperMicro servers)
  block:
    - name: SuperMicro Power ON
      community.general.redfish_command:
        category: Systems
        command: PowerOn
        baseuri: "{{ hostvars[item]['bmc_address'] }}"
        username: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"

    - name: Check if there is a ISO mounted on the SuperMicro
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/1/VirtualMedia/CD1"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: GET
        validate_certs: no
        force_basic_auth: yes
        return_content: yes
      register: cd1_contents

    - name: Unmount SuperMicro ISO
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/1/VirtualMedia/CD1/Actions/VirtualMedia.EjectMedia"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: POST
        headers:
          content-type: application/json
          Accept: application/json
        body: {}
        body_format: json
        validate_certs: no
        force_basic_auth: yes
        return_content: yes
      when: cd1_contents.json.Inserted | bool == True

    - name: Set Boot for the SuperMicro
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Systems/1"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: PATCH
        headers:
          content-type: application/json
          Accept: application/json
        body: '{"Boot":{"BootSourceOverrideEnabled":"Continuous","BootSourceOverrideTarget":"Hdd"}}' # Despite what the docs say HDD is not the correct value
        body_format: json
        force_basic_auth: yes
        validate_certs: no
        return_content: yes

    - name: Restart the SuperMicro
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: POST
        headers:
          content-type: application/json
          Accept: application/json
        body: '{"ResetType": "ForceRestart"}'
        body_format: json
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
