- name: Check required domain {item} exists
  ansible.builtin.shell:
    cmd: "{{ required_binary }} {{ item.value }} +short"
  register: res
  changed_when: false

- name: Check stdout for expected IP address
  ansible.builtin.set_fact:
    failed_domains: "{{ (failed_domains | default({})) | combine(
        {item.value: {
          'stdout': res.stdout,
          'stderr': res.stderr,
          'expected': expected_answers[item.key],
        }}
      ) }}"
  when: expected_answers[item.key] not in res.stdout
