secure: false
ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
ASSISTED_INSTALLER_BASE_URL: "{{ secure | ternary('https', 'http') }}://{{ ASSISTED_INSTALLER_HOST }}:{{ ASSISTED_INSTALLER_PORT }}/api/assisted-install/v1"
URL_ASSISTED_INSTALLER_CLUSTER: "{{ ASSISTED_INSTALLER_BASE_URL }}/clusters/{{ ADD_HOST_CLUSTER_ID }}"
