# This is for backwards compatabilty

- name: Setup vlan interface
  when: vm_vlan_tag is defined
  block:
    - name: Build vlan interface definition
      set_fact:
        vlan_interface:
          name: "{{ vm_vlan_name }}"
          type: vlan
          vlan:
            interface: "{{ vm_bridge_interface }}"
            tag: "{{ vm_vlan_tag }}"

    - name: Set vm_bridge_port_name as vlan interface name
      set_fact:
        vm_bridge_port_name: "{{ vm_vlan_name }}"

- name: Build bridge interface definition and add to interfaces list
  set_fact:
    network_config_interfaces:
      - type: linux-bridge
        name: "{{ vm_bridge_name }}"
        addresses:
          ipv4:
            - ip: "{{ vm_bridge_ip }}"
              prefix: "{{ vm_bridge_prefix }}"
        bridge:
          stp: True
          port:
            name: "{{ vm_bridge_port_name }}"

- name: Append vlan to network_config_interfaces
  set_fact:
    network_config_interfaces: "{{ network_config_interfaces + [vlan_interface] }}"
  when: vm_vlan_tag is defined

- name: Build network_config
  set_fact:
    network_config:
      interfaces: "{{ network_config_interfaces }}"
