vm_spec_defaults:
  master:
    memory: 16384
    vcpu: 6
    disk_size: 120
  worker:
    memory: 30000
    vcpu: 8
    disk_size: 120

vm_group_params:
  master:
    memory: "{{ vm_spec_master_memory | default(vm_spec_defaults.master.memory) }}"
    vcpu: "{{ vm_spec_master_vcpu | default(vm_spec_defaults.master.vcpu) }}"
    disk_size: "{{ vm_spec_master_disk_size | default(vm_spec_defaults.master.disk_size) }}"
  worker:
    memory: "{{ vm_spec_worker_memory | default(vm_spec_defaults.worker.memory) }}"
    vcpu: "{{ vm_spec_worker_vcpu | default(vm_spec_defaults.worker.vcpu) }}"
    disk_size: "{{ vm_spec_worker_disk_size | default(vm_spec_defaults.worker.disk_size) }}"

vm_node_prefix: "{{ cluster_name }}_"
