---
# defaults file for create_day2_cluster

secure: false
disconnected: False
manifests: True

mirror_registry: "{{ hostvars['registry_host']['registry_fqdn'] }}:{{ hostvars['registry_host']['registry_port'] }}"


ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] | default(ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])) }}"
ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] | default(8090) }}"
ASSISTED_INSTALLER_BASE_URL: "{{ secure | ternary('https', 'http') }}://{{ ASSISTED_INSTALLER_HOST }}:{{ ASSISTED_INSTALLER_PORT }}/api/assisted-install/v2"

http_proxy: ""
https_proxy: ""
no_proxy: ""

# HTTP Basic Authentication
HTTP_AUTH_USERNAME: "none"
HTTP_AUTH_PASSWORD: "none"

manifest_templates:
  - 50-worker-nm-fix-ipv6.yml
  - 50-worker-remove-ipi-leftovers.yml

fetched_dest: "{{ repo_root_path }}/fetched"
