---
- name: Check openshift_full_version is set
  fail:
    msg: openshift_full_version must be set and not empty
  when: (openshift_full_version is not defined) or (openshift_full_version == "")

- name: Check openshift_full_version is has at last two parts
  block:
    - name: Split openshift_full_version
      set_fact:
        openshift_version_parts: "{{ openshift_full_version.split('.') }}"
    - name:
      fail:
        msg: openshift_full_version does not have at least two parts
      when: openshift_version_parts | length < 2
