---
# defaults file for install_cluster

install: True
secure: False

ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] | default(ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])) }}"
ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] | default(8090) }}"
ASSISTED_INSTALLER_BASE_URL: "{{ secure | ternary('https', 'http') }}://{{ ASSISTED_INSTALLER_HOST }}:{{ ASSISTED_INSTALLER_PORT }}/api/assisted-install/v2"
URL_ASSISTED_INSTALLER_CLUSTER: "{{ ASSISTED_INSTALLER_BASE_URL }}/clusters/{{ cluster_id }}"

# HTTP Basic Authentication
HTTP_AUTH_USERNAME: "none"
HTTP_AUTH_PASSWORD: "none"

fetched_dest: "{{ repo_root_path }}/fetched"

single_node_openshift_enabled: "{{ is_valid_single_node_openshift_config | default(false) }}"

host_discovery_states:
  - discovering
  - known
  - pending-for-input
  - insufficient
  - ready

cluster_installation_states:
  - installing
  - installing-pending-user-action
