- name: Setup NTP
  hosts: ntp_host
  gather_facts: False
  vars:
    SETUP_NTP_SERVICE: "{{setup_ntp_service | default(True)}}"
  pre_tasks:
    - name: Setup facts
      setup:
      when: SETUP_NTP_SERVICE | bool
  roles:
    - role: setup_ntp
      when: SETUP_NTP_SERVICE | bool
