- name: Deploy sushy tools
  hosts: vm_hosts
  gather_facts: False
  vars:
    SETUP_SUSHY_TOOLS: "{{ setup_sushy_tools | default(setup_vms | default(True)) }}"
  pre_tasks:
    - name: Setup facts
      setup:
      when: SETUP_SUSHY_TOOLS | bool
  roles:
    - name: setup_sushy_tools
      when: SETUP_SUSHY_TOOLS | bool
