http_store_dir : "{{ iso_download_dest_path | default('/opt/http_store/data') }}"
http_port: 80
http_host: "{{ discovery_iso_server | default('http://' + hostvars['http_store']['ansible_host']) }}:{{ http_port }}"
test_file_name: http_test
