---
# defaults file for create_cluster

secure: False
create: True
manifests: True
schedulable_masters: True

fetched_dest: "{{ repo_root_path }}/fetched"

disconnected: "{{ use_local_mirror_registry | default(setup_registry_service | default(true)) }}"
mirror_registry_fqdn: "{{ hostvars['registry_host']['registry_fqdn'] | default(hostvars['registry_host']['ansible_fqdn']) }}"
mirror_registry_port: "{{ hostvars['registry_host']['registry_port'] | default(5000) }}"
mirror_registry: "{{ mirror_registry_fqdn }}:{{ mirror_registry_port }}"

ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] | default(ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])) }}"
ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] | default(8090) }}"
ASSISTED_INSTALLER_BASE_URL: "{{ secure | ternary('https', 'http') }}://{{ ASSISTED_INSTALLER_HOST }}:{{ ASSISTED_INSTALLER_PORT }}/api/assisted-install/v2"
URL_ASSISTED_INSTALLER_CLUSTERS: "{{ ASSISTED_INSTALLER_BASE_URL }}/clusters"

HTTP_AUTH_USERNAME: "none"
HTTP_AUTH_PASSWORD: "none"
http_proxy: ""
https_proxy: ""
no_proxy: ""

single_node_openshift_enabled: "{{ is_valid_single_node_openshift_config | default(false) }}"

# Accepted values for "High Availability Mode"
#
# 1. 'None' (when `is_valid_single_node_openshift_config` evaluates to True)
#     Requires one master node and no worker nodes -- SNO.
# 2. 'Full' (otherwise)
#     Requires at least three master nodes for High Availability.
high_availability_mode: "{{ single_node_openshift_enabled | ternary('none', 'full') }}"
has_workers: "{{ (groups['workers'] | default([])) | length > 0 }}"

create_body_extras: {}
cluster_id_filename: "cluster.txt" # This default is for backwards compatability
