galaxy_info:
  author: Hanen Garcia
  description: Boot from disk
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.9
  galaxy_tags: []
dependencies:
  - role: validate_inventory
